name: Build and Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Build Docker image
      run: docker build -t gdg-docs:latest .
      
    - name: Test Docker image
      run: |
        docker run -d --name test-container -p 8080:8080 gdg-docs:latest
        sleep 10
        curl -f http://localhost:8080 || exit 1
        docker stop test-container